# Numpy Cheat Sheet

Important commands for `creating` and `manipulating` numpy arrays. 

In [2]:
import numpy as np
import matplotlib.pyplot as plt

## Working with np.random
Create random array with uniform distribution in the given interval.

In [6]:
N = 10_000_000
data = np.random.uniform(low=0, high=5, size=N)
print(sum(data) / N)

2.500069368883187


create random numbers with `np.random.seed`

In [14]:
np.random.seed(999)
print(np.random.rand(5))

np.random.seed(999)
print(np.random.rand(6))

[0.80342804 0.5275223  0.11911147 0.63968144 0.09092526]
[0.80342804 0.5275223  0.11911147 0.63968144 0.09092526 0.33222568]


create random numbers without `np.random.seed`

In [15]:
print(np.random.rand(5))
print(np.random.rand(5))

[0.42738095 0.55438581 0.62812652 0.69739294 0.78994969]
[0.13189035 0.34277045 0.20155961 0.70732423 0.03339926]


## Create np arrays
Linespace for creating N numbers equally spaced from start to stop.

In [16]:
equally_spaced = np.linspace(start=2, stop = 5_000, num=N)
print(equally_spaced)

equally_spaced_2, _step = np.linspace(start=2, stop = 5_000, num=N, retstep=True)
print(_step)

[2.0000000e+00 2.0004998e+00 2.0009996e+00 ... 4.9999990e+03 4.9999995e+03
 5.0000000e+03]
0.000499800049980005


Use `np.arage` for the python-equivalent range() with [start, stop):

In [17]:
print(np.arange(5,10))

[5 6 7 8 9]


Create matrix by simply `stacking` the column vectors:

In [53]:
first_col = np.arange(5)

result = np.column_stack(
    [np.power(first_col, m) for m in range(1,4)]
)

print(result)

[[ 0  0  0]
 [ 1  1  1]
 [ 2  4  8]
 [ 3  9 27]
 [ 4 16 64]]


## sorting/ permutating arrays

First, using `np.shuffle` for a random shuffle.

In [24]:
N_numbs = 10
numbs = np.arange(1,N_numbs)
print(numbs)
np.random.shuffle(numbs)
print(numbs)


[1 2 3 4 5 6 7 8 9]
[1 5 8 6 7 3 9 4 2]


If you want to permutate more than 1 array the same way:

In [35]:
N_numbs = 5

numbers = np.arange(N_numbs)
numbers_squared = np.square(numbers)

def print_numbs(nums, nums_squared):
    for i, j in zip(nums, nums_squared):
        print(f"{i} squared is {j}")

print_numbs(numbers, numbers_squared)

print("--- Now, lets permutate both the same way:")

shuffler = np.random.permutation(N_numbs)
numbers = numbers[shuffler]
numbers_squared = numbers_squared[shuffler]
print_numbs(numbers, numbers_squared)


0 squared is 0
1 squared is 1
2 squared is 4
3 squared is 9
4 squared is 16
--- Now, lets permutate both the same way:
0 squared is 0
3 squared is 9
1 squared is 1
4 squared is 16
2 squared is 4


## Manipulate Size/ Shape of data

In [39]:
m = np.random.uniform(low=-1, high=1, size=(3,2,3))
print(m)
print("Dimension of m is: ", m.shape)


[[[ 0.27218156  0.5495661  -0.42668385]
  [-0.40195247 -0.45870675 -0.4422259 ]]

 [[-0.84580324  0.08228117 -0.98947754]
  [ 0.48264228  0.68733622 -0.78443007]]

 [[-0.46722063 -0.67770138  0.11881497]
  [ 0.90979778 -0.61742101  0.87127291]]]
Dimension of m is:  (3, 2, 3)


You can also reshape into other dimensions:

In [50]:
line = np.arange(8)

matrix = np.reshape(line, (2,2,2))
print(matrix)
print("Shape is: ", matrix.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Shape is:  (2, 2, 2)


Splitting arrays (python way):

In [54]:
line = np.arange(9)
split_index = 3

line_1 = line[:3]
line_2 = line[3:]

print("first line:", line_1)
print("second line:", line_2)

first line: [0 1 2]
second line: [3 4 5 6 7 8]


Splitting arrays with numpy:

In [67]:
line = np.arange(9)
m = np.reshape(line, (3,3))
print(m)

def split(axis):
    t1, t2 = np.split(m, (1,), axis=axis)
    print("---")
    print(t1, t1.shape)
    print("---")
    print(t2, t2.shape)
split(0)

print("++++++++++")
split(1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
---
[[0 1 2]] (1, 3)
---
[[3 4 5]
 [6 7 8]] (2, 3)
++++++++++
---
[[0]
 [3]
 [6]] (3, 1)
---
[[1 2]
 [4 5]
 [7 8]] (3, 2)
