In [2]:
import numpy as np


In [16]:
# 1. - Standard linear regression
X = np.array((1,1,1,1,-1,-0.5,0,1.5)).reshape(2,4).T
Y = np.array((0,-1,2,1))

w_star = np.linalg.inv(X.T @ X)@X.T@Y
print("w_star = ", w_star)

ls_error = 0.5 * (Y - X@w_star).T @(Y - X@w_star)
print("error = ", ls_error)


w_star =  [0.5        0.57142857]
error =  1.9285714285714288


In [23]:
# 2. - Regularized linear regression
X = np.array((1,1,1,1, -1.5, -1, 0.5, 1.5)).reshape(2,4).T
Y = np.array((2, 1.5, 1.5, 1))

lambda_ = 10

w_star_reg = np.linalg.inv(X.T @ X + 2*lambda_*np.eye(2))@X.T@Y
print("w_star_regularized = ", w_star_reg)

ls_error_reg = 0.5 * (Y - X@w_star_reg).T @(Y - X@w_star_reg)
print("error for regularized w*: ", ls_error_reg)

print("------")
# calc. w0 (unregularized)
w_star = np.linalg.inv(X.T @ X)@X.T@Y
print("w_star (unregularized) = ", w_star)

ls_error = 0.5 * (Y - X@w_star).T @(Y - X@w_star)
print("error for unregularized = ", ls_error)

print("As expected, the loss for the unregularized function is lower.")


w_star_regularized =  [ 0.24828005 -0.08255767]
error for regularized w*:  3.2276949645429682
------
w_star (unregularized) =  [ 1.46703297 -0.26373626]
error for unregularized =  0.05219780219780219
As expected, the loss for the unregularized function is lower.


In [42]:
# 3 - Generalized Linear regression
PSI = np.array((1,1,1, -3, 1, 9, 9, 1, 81)).reshape(3,3).T
Y = np.array((2.8, 0.4, 0.2))

print(X)
print(Y)

print("___")
A = PSI.T @ PSI

B = PSI.T @ Y
print("PSI @ Y = ", B)

print(A)
det = np.linalg.det(A)
print("det = ", det)

w_star = np.linalg.inv(A) @ B
print("w_star  = ", w_star)

# Again, but now with M = 1, psi_0(x) = 1 and psi_1(x) = sign(x)
print("__________")
PSI_SIGN = np.array((1,1,1,-1,1,1)).reshape(2,3).T
print("New PSI = ", PSI_SIGN)

C = np.linalg.inv(PSI_SIGN.T @ PSI_SIGN)
D = PSI_SIGN.T @ Y

w_star_sign = C @ D
print("w_star sign = ", w_star_sign)


[[ 1 -3  9]
 [ 1  1  1]
 [ 1  9 81]]
[2.8 0.4 0.2]
___
PSI @ Y =  [ 3.4 -6.2 41.8]
[[   3    7   91]
 [   7   91  703]
 [  91  703 6643]]
det =  147456.0
w_star  =  [ 0.85625    -0.50416667  0.04791667]
__________
New PSI =  [[ 1 -1]
 [ 1  1]
 [ 1  1]]
w_star sign =  [ 1.55 -1.25]
